### ISSUE TITLE
error when editing stats

### ISSUE THREAD

**Issue by kmerfeld** [gvorbeck/codex-quest#288]
When on the full character sheet, if I edit an ability (write number, increment, or roll) I get a `TypeError: a.split(...)[1] is undefined` error in the console and the screen goes white.

I think its not passing the dice correctly to src/support/statSupport.ts `getHitDice()`

**Comment by gvorbeck** [comment]
Wowwwww,
That's a powerful error. Thank you for bringing it to my attention. I'll try to have a fix for this in the coming days. Good catch.

**Comment by gvorbeck** [comment]
Oof, I think I figured out the problem.

In order to make sure a user isn't able to game the system or break the rules when creating a character, I erase a character's stats when making certain changes. (ex: If they changes an ability score, I erase things like Race, Class, Hit Dice, etc because certain choice become unavailable with certain ability scores). This also happens for things like changing a Race selection; I would erase any previously made Class selections in order to make sure they can only have a Class that pertains to that original Race selection.

The solution is going to be checking to see if the user is on the character sheet page. If so, disable all those erasures and allow the user to futz with their completed character no matter what. Then the Hit Dice will not be gone and the page wont crash.

**Comment by gvorbeck** [comment]
This is fixed with codex.quest v2.7.5, I fixed an inadvertent hardcoding of the behavior described above. The ability table now recognizes if it is on the Character Sheet page and does not wipe out other stats when adjusting for the new ability. Thanks again for bringing this to my attention.
